### ISSUE TITLE
[QST] pickup&delivery

### ISSUE THREAD

**Issue by LeoAlle** [NVIDIA/cuOpt-Resources#13]
Hi,
I'm using cuOpt-Resources server with an instance with more ore less 200 pickup&delivery pairs. I get a solution in less than 1 second even if I've put a time limit of 2 minutes. The solution cost i get (if it represents the total distance of all routes) could be better though because I have a benchmark.
Why does the algorithm stop so early?

**Comment by afender** [comment]
Hi @LeoAlle, thanks for your question! Could you share a minimal way to reproduce this? There are multiple paths the solver can take depending on the settings and this would help us better diagnose what's going on. We typically use this public [collection](https://www.sintef.no/projectweb/top/pdptw/li-lim-benchmark/) to monitor performance on pickup&delivery if that helps.
Please make sure you use the latest version (22.10). We are actively working on pickup&delivery and expect results to keep improving in the coming releases.

**Comment by LeoAlle** [comment]
Hi @afender,  
Thank you for your quickly response.
So the objective is to minimize the number of vehicles used?
If you want, I can share with you the outoput I get now where you can also find the input I've used for this solver trial so that  we can compare the results. Maybe I'm missing something, but I'd like to know if these are the actual results on this istance.

**Comment by LeoAlle** [comment]
I also confirm to you that I'm using the latest version.

**Comment by afender** [comment]
Yes the primary objective is to reduce the number of vehicles currently. The solution cost you get is the distance of all routes. The rationale is that it is often costlier to add and operate an additional vehicle compared to doing a few more miles with a smaller fleet. We plan on making this more flexible in the coming releases.

As of 22.10; a standard pick up and delivery (PDP) with time windows should run for the allocated time limit. More complex variants of PDP can return after finding the most efficient feasible solution among a finite set of candidates, which could be why it returned earlier in your case.

**Comment by LeoAlle** [comment]
Ok thank you. 
If you want I can share with you the output so that you can reproduce the run as you asked before (I've seen that in the output there is also the input).
Let me know.
It could be good to compare the results to make sure I'm using the solver correctly.

**Comment by afender** [comment]
Sure! Happy to take a look at a repro to double check. Thanks.

**Comment by LeoAlle** [comment]
Ok this is the output I get up to now.
[Cartella github.zip](https://github.com/NVIDIA/cuOpt-Resources/files/10057683/Cartella.github.zip)

**Comment by LeoAlle** [comment]
Hi @afender, are there any news about the results? 

I'm doing some other tests of the solver with my instances and I still don't really understand its optimization logics. I understand that the total distance of the routes is the second objective, but the results I get in this particular KPI is very high comparing with my other benchmarks. I've noticed that sometimes it builds routes where after every delivery point the vehicle comes back to the depot to pick other goods. Why does it not merge more than one pick before leaving the depot to do the deliveries?

**Comment by rg20** [comment]
Hi @LeoAlle, 
Thanks for your interest in `cuOpt` and also sharing the output. The 22.10 version returns a feasible solution as soon as we find one, for most `PDP` variants. The future versions will improve feasible solutions until the time limit is reached for the `PDP` variants as well. 

With regards to the latest comment regarding vehicles going back to the depot to pick up other goods, are you modeling pure delivery (`CVRPTW`) cases using `PDP`? If so, you can directly specify the problem as `CVRPTW` by avoiding pickup-delivery pairs. This approach should generate better results.  If the problem is in fact a pure `PDP`, there can be a few reasons such as capacity constraints that prevent the merging of pick-up orders.

**Comment by LeoAlle** [comment]
Hi @rg20, 
thanks for your answer. Maybe the reason why I get bad results in term of total distance is the one you suggest. 

In the output I've sent to you I'm modeling the problem as a PDP because I have more than one starting depot and sometimes I have a points where I need to pick goods, but also to deliver something else. Is my approach wrong?
Do i need to model this kind of problem differently? 

Anyway, in the zip folder I've shared with you there is also the input I've used. If it's not a problem it could be interesting for me also to know if the results I get for that kind of modeling approach are the actual ones for cuOpt.

Let me know, thanks.

**Comment by rg20** [comment]
Hi @LeoAlle, 
Thanks for your patience appreciate your feedback. 

I could reproduce the results. I get slightly better results than what you provided (122 vehicles instead of 125 and 10% reduction in distance/cost.  

The good news is that I could improve the results significantly with our improved heuristics.  For the model you provided, the final cost/distance achieved was about 9 times better (9710340 vs your result of 87088616) and the vehicle count is reduced to 109.  The improved heuristics for `PDP` problems will be available in the coming releases.  

Meanwhile, if you have any `CVRPTW` cases, please feel free to try them out.

**Comment by LeoAlle** [comment]
Hi @rg20,
Thanks for your feedbacks. I'm already trying to test the solver with CVRPTW cases and it seems actually to work better as you suggested. If you are interested I can also share with you some CVRPTW results so we can compare them.

Just to know, what is the solver configuration that you used to solve my PDP example? Cause I would like to understand why I get 125 vehicles and 10% more in total distance.

**Comment by rg20** [comment]
@LeoAlle 
I used the same configuration as yours. But I was using the development branch while you were using the 22.10 branch. That could explain the differences in results.

**Comment by LeoAlle** [comment]
Ok @rg20, perfect!

Here I'm sharing the output and input for a CVRPTW case. 
I'd appreciate if we could compare the results even in this case to make sure I'm using the solver correctly.
[CVRPTW.zip](https://github.com/NVIDIA/cuOpt-Resources/files/10133931/CVRPTW.zip)

**Comment by rg20** [comment]
> Ok @rg20, perfect!
> 
> Here I'm sharing the output and input for a CVRPTW case. I'd appreciate if we could compare the results even in this case to make sure I'm using the solver correctly. [CVRPTW.zip](https://github.com/NVIDIA/cuOpt-Resources/files/10133931/CVRPTW.zip)

Thanks! 
Can you comment on the quality of the solution with regards to number of vehicles used, and the total cost?

**Comment by LeoAlle** [comment]
Yes! The total distance is 8370639 and the used vehicles are 58 if I've solved it correctly.
I've used "objectives" in the solver configuration to consider both distance and vehicles with the same weight in the objective function. 
It seems quite good as a result. Sure it's way better than solving the same istance as a PDP, but I still have to add some other constraints to the problem so I expect the solution to worsen a little. But before that I want to make sure these are the actul results for this CVRPTW.

**Comment by LeoAlle** [comment]
I don't know if the response I gave you is the one you were looking for with your last question. 
Let me know.

**Comment by LeoAlle** [comment]
Ok

**Comment by LeoAlle** [comment]
Ok thank you @rg20.
