### ISSUE TITLE
[QST] how to input data for "set_task_data" api

### ISSUE THREAD

**Issue by immnas** [NVIDIA/cuOpt-Resources#14]
I have doubt regarding cupot server api "set_task_data" input parameters 
the "task_time_windows" what's these two parameters for each location shown in example? 
https://docs.nvidia.com/cuopt/examples/00_server.html
and what's the unit to calculate this?
For Example: for one particular location we want to set time slot between 1:00 PM to 2:00 PM.
how we can add this slot in the "task_time_windows" parameter?
while adding "task_time_windows" we calculated the time in seconds from 12:00AM Mid night to 1:00 PM (46800).
similarly we added for 2:00PM (50400).
I see similar function for python is data_model set_order_time_windows.
is it right?

**Comment by rg20** [comment]
Hi @immnas,  

The two parameters correspond to the earliest and the latest start time for each task.  The units should be aligned with the edges used in the waypoint graph if the waypoint graph is provided, or should be aligned with the travel time matrix if a matrix is provided as input.  

With regards to seconds calculated from midnight. The approach would be correct as long as the matrix or edges in the waypoint graph are also specified in seconds.

**Comment by Iroy30** [comment]
Hi @immnas Let us know if were able to clarify the doubts and if we can go ahead and close this issue
