### ISSUE TITLE
How to solve a routing problem with both vehicle start end constraints and pickup delivery constraints?[QST]

### ISSUE THREAD

**Issue by ajinra020307** [NVIDIA/cuOpt-Resources#21]
I am trying to solve a pickup delivery problem, These are the parameters

1. Vehicles will have a start and end location (dynamic for every vehicle)
2. List of waypoints pickup and delivery

I need to apply vehicle start-end constraint and pickup-delivery constraint.

I did the following.

I added the vehicle starts and ends as waypoints to the solver.
Then i add start-end vehicle constraint using set_vehicle_locations function
Then i tried to setup pickup delivery constraint using  set_pickup_delivery_pairs function

But the function expects the vehicle start and end location as a pickup delivery pair.
Please tell me how to handle this case?

**Comment by rg20** [comment]
Hi @ajinra020307 , 

Suppose that you have `nlocations` number of locations, corresponding `nlocationsXnlocations` matrix,  `npairs` of pickup and delivery pairs, and 'nvehicles' number of vehicles in the fleet, you have to set the following: 

1. `add_cost_matrix` and `add_transit_time_matrix`. The second matrix is required only if you have time windows 
2. `set_order_locations` to set the locations of all orders. Here pickup and delivery are treated as two separate orders, so the vector/series should have the size of `2*npairs`
3. 'set_pickup_delivery_pairs' to set the order number corresponding to each pickup and delivery. Here the pairs do not correspond to the locations, but they are indirections into the `order_locations` array.  

See a detailed example [here](https://github.com/NVIDIA/cuOpt-Resources/blob/branch-22.10/notebooks/routing/python/pdptw_mixed_fleet.ipynb)

**Comment by ajinra020307** [comment]
@rg20 Thanks for your response

What if i had to handle dynamic vehicle starts and ends for each vehicle?

For example if my problem has 2 vehicles both having a start and end location and 2 locations (one delivery and one pickup).
How will i setup the delivery pair?

**Comment by rg20** [comment]
Let's say you have 6 locations in total (0 to 5).  And,
vehicle 0: start location 0, return location 1
vehicle 1: start location 2, return location 3 

one pair: pickup at location 4, delivery at location 5 


```
vehicle_start_locations = cudf.Series([0, 2])
vehicle_return_locations = cudf.Series([1, 3])

data_model.set_vehicle_locations(vehicle_start_locations, vehicle_return_locations) 


order_locations = cudf.Series([4, 5]) # order 0 is the pickup, order 1 is the delivery
# all the time windows for orders should have a size of two and the zeroth entry should 
# correspond to pickup and the next one should correspond to delivery

data_model.set_order_locations(order_locations) 

pickup_order_indices = cudf.Series([0]) 
delivery_order_indices = cudf.Series([1])
data_model.set_pickup_delivery_pairs(pickup_order_indices, delivery_order_indices)
```

**Comment by ajinra020307** [comment]
okay Thanks
Still have a doubt, 
what should be the size of cost and time matrix? is it  2 * 2 or 6 * 6?
in dataModel i should provide 2 or 6 as number of locations?

**Comment by rg20** [comment]
The matrices should be of 6x6 size in this example. This is because the solver has to take into account the cost/time of travel from starting point to a service location and vice versa.   

The indices specified in `order_locations`, `vehicle_start_locations`, and `vehicle_return_locations` indicate the row and column numbers in the matrix.

**Comment by ajinra020307** [comment]
@rg20 Its working , Thanks for the help
