### ISSUE TITLE
New Release 22.12

### ISSUE THREAD

**Issue by LeoAlle** [NVIDIA/cuOpt-Resources#25]
Hi, 
what's new about the 22.12 release? Is it possible to solve PDP now?

**Comment by rg20** [comment]
@LeoAlle, 

You can find the release notes [here](https://github.com/NVIDIA/cuOpt-Resources/discussions/22). The support for PDP is similar to the 22.10 version. The new advancements will come in upcoming releases.

**Comment by LeoAlle** [comment]
Thank you @rg20
