### ISSUE TITLE
Matrices in case of sub-instances

### ISSUE THREAD

**Issue by LeoAlle** [NVIDIA/cuOpt-Resources#26]
Hi, 
I'm using v.22.10.1 of the solver

When I give the matrices in input and I want to consider a complete instance and then the same instance, but splitted in more sub-instances is it possible to give always the same matrices?
Or do I have to cut the matrix when some of the points of the complete instance are no more in the sub-instance?

**Comment by rg20** [comment]
Hi @LeoAlle , 

You do not have to modify the matrices as long as the `task_locations` are updated accordingly. The `task_locations` vector consists of customer location indices. For example, you can have a matrix corresponding to 100 locations, but only have customers at 10 of those locations. In that case, all the task-related data (such as time windows and demand, etc) will be of dimension 10.

**Comment by LeoAlle** [comment]
Ok @rg20, thank you for the response.
