### ISSUE TITLE
[QST] can i add vehicle capacity and goods capacity

### ISSUE THREAD

**Issue by immnas** [NVIDIA/cuOpt-Resources#29]
can i add vehicle capacity and goods capacity?
if my vehicle capacity in terms of height, widths and length.
and some other parameters like milage, carbon footprint.
as well as i add good capacity like height, widths and length.
if possible yes ..what's the API for that?
and in answer will i get the which vehicle will carry which goods in optimised solution.

**Comment by rg20** [comment]
Hi @immnas, 
It is possible to add multiple capacities. These are represented as capacity dimensions in the solver.  For each capacity constraint, you can call `data_model.add_capacity_dimension` if you are using python API or have multiple columns in `task_data["demand"]` and `fleet_data["capacities"]` if you are using server API.  For each dimension, there should be one vector `capacities` of length `fleet_size` and `demand` of length `num_orders/tasks`. 

For the example you mentioned, you can have three separate dimensions for height, width, and length. However, this means that sum of the heights of all goods in the vehicle will be less than the height of the vehicle and similarly for length and width. This constraint may be too restrictive.

**Comment by immnas** [comment]
ok, Do I get the route planning where it will mentioned ..how many vehicles and which goods (vehicle wise) for any particular destination?

**Comment by rg20** [comment]
Yes. The solver returns an `Assignment` object that has all the information. There are several notebook examples for your reference [here](https://github.com/NVIDIA/cuOpt-Resources/tree/branch-22.12/notebooks/routing/python). 

If you are using the server API, you can find examples [here](https://github.com/NVIDIA/cuOpt-Resources/tree/branch-22.12/notebooks/routing/microservice).

**Comment by Iroy30** [comment]
Hi @immnas Following up on the issue, were you able to add the add the constraints and inspect the results?
