### ISSUE TITLE
How to pass set_order_time_windows ? [QST]

### ISSUE THREAD

**Issue by ajinra020307** [NVIDIA/cuOpt-Resources#30]
I have set the order location using set_order_locations.
Then i setup pickup delivery  pairs using the index of orderlocations array

How to set time windows? Do i need to pass the values using orderlocations index?

**Comment by rg20** [comment]
Hi @ajinra020307, 

Time windows are associated with the orders.  For example `earliest_time[12] ` corresponds to the earliest time order 12 has to be served.  `order_locations[12]` will contain the location index of the corresponding order.  Either pickup or delivery indices will have 12 in them depending on if the order is pickup or delivery. If let's say, pickup[5] is 12, delivery[5]  is the order index of the corresponding delivery order (not location).
