### ISSUE TITLE
Objective function

### ISSUE THREAD

**Issue by LeoAlle** [NVIDIA/cuOpt-Resources#31]
Hi, 
I'm doing some tests and I've added the "Objectives" in the solver configuration putting the same weight equal to 100000 for the distance (cost) and vehicles. 
Is it possible that maybe the number of vehicles is still considered as the main objective even if the weight is the same?
I'm asking because this is what it seems considering the results I'm obtaining.

**Comment by hlinsen** [comment]
Hi @LeoAlle,
Both dimensions will be weighted equal but your intuition is correct. By nature the solver tries to minimize the number of vehicles. Depending on the input and problem type you might not see a noticeable change even with objective function set.

**Comment by LeoAlle** [comment]
Ok @hlinsen, 
thanks a lot for your response.
