### ISSUE TITLE
[QST] in case of failure can i get the failure reason

### ISSUE THREAD

**Issue by immnas** [NVIDIA/cuOpt-Resources#33]
hi,
while calling api /cuopt/get_optimized_routes we get {"detail":"Failed to find solution with given constraints"}.
is it possible to know due to which constrain this failed?
or is it possible to mentioned or prioritise few constrain route optimiser must follow?
i.e. one constrain i dont want to strictly follow if i dont get any route. Avoid that constrain and still give me route with reason.

**Comment by immnas** [comment]
we have play enabled following   "error_logging":true   "verbose_mode": true but still didnt get any reason why it got failed?
what i understand that  "drop_infeasible_tasks": "true" we can get answer all the time  
{
            "time_limit": 5,
            "number_of_climbers": 1024,
            "error_logging":true,
            "verbose_mode":true,
            "drop_infeasible_tasks": false
        }

**Comment by rg20** [comment]
@immnas, 

It is not possible to prioritize constraints at the moment. So even if one constraint can not be satisfied, the solver returns failure and an empty route. With drop infeasible tasks enabled, the solver does not fulfill all the customer orders and returns a partial route and a list of unfulfilled orders.  

You can also provide more vehicles in the fleet data to get a feasible solution if it makes sense for your problem.

**Comment by immnas** [comment]
could you tell me if i can get the detail about the error?

**Comment by rg20** [comment]
@immnas, 

The solver does not report the details of the error at the moment when using the server API.

**Comment by Iroy30** [comment]
@immnas, we are planning to add that to server API next release. In the meanwhile using the python SDK could provide better insight
